/**
 * API 统一错误码（开发文档 §13.1、§13.4）。
 */

export const ERROR_CODES = {
  // 通用
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // 角色
  AVATAR_VERSION_CONFLICT: 'AVATAR_VERSION_CONFLICT',
  AVATAR_PROFILE_INVALID: 'AVATAR_PROFILE_INVALID',
  // 资产
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_INCOMPATIBLE: 'ASSET_INCOMPATIBLE',
  ASSET_NOT_PUBLISHED: 'ASSET_NOT_PUBLISHED',
  // 导入
  IMPORT_FILE_INVALID: 'IMPORT_FILE_INVALID',
  IMPORT_FORMAT_UNSUPPORTED: 'IMPORT_FORMAT_UNSUPPORTED',
  IMPORT_RIG_INCOMPLETE: 'IMPORT_RIG_INCOMPLETE',
  IMPORT_LIMIT_EXCEEDED: 'IMPORT_LIMIT_EXCEEDED',
  IMPORT_LICENSE_MISSING: 'IMPORT_LICENSE_MISSING',
  IMPORT_NOT_VALIDATED: 'IMPORT_NOT_VALIDATED',
  // 任务
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_FAILED: 'JOB_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  requestId: string;
  details?: unknown;
}
